version: '3.9'

services:
  chatglm3:
    image: registry.cn-shanghai.aliyuncs.com/jerryliang/chatglm3:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    environment:
      - TZ=Asia/Shanghai
      - TOKENIZER_PATH=/mnt/chatglm3-6b
      - MODEL_PATH=/mnt/chatglm3-6b
    ports:
      - 9000:9000
    volumes:
      - /mnt:/mnt
