name: docker build
on: 
  push:
    branches: [ chatglm2-6b-32K-tx ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # 设置 QEMU, 后面 docker buildx 依赖此.
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        
            # 设置 Docker buildx, 方便构建 Multi platform 镜像
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        # 登录 docker hub
        - name: Login to DockerHub
          uses: docker/login-action@master
          with:
            # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
            # DOCKERHUB_USERNAME 是 docker hub 账号名.
            # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
            registry: ccr.ccs.tencentyun.com
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        # 构建镜像, 并打 tag
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ccr.ccs.tencentyun.com/jerryliang/chatglm2:latest