name: docker build
on: 
  push:
    branches: [ chatglm2-6b-32K-tx ]

jobs:
    gd:
      runs-on: self-hosted
      steps:
      #- name: Free Disk Space (Ubuntu)
      #  uses: jerryliang122/free-disk-space@main
      #  with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
      #    tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
      #    android: true
      #    dotnet: true
      #    haskell: true
      #    large-packages: true
      #    docker-images: true
      #    swap-storage: true   
      
      - name: Checkout
        uses: actions/checkout@v2
          
      #- name: clone chatglm2-6b-32K
      #  run: |
      #    git clone https://huggingface.co/THUDM/chatglm2-6b-32k
      #    cd chatglm2-6b-32k && rm -rf .git

      # 登录腾讯docker
      - name: Login to Tencent docker
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

 
      - name: Build docker image
        run: |
          docker build -t ccr.ccs.tencentyun.com/jerryliang/chatglm2:last . 
          docker push ccr.ccs.tencentyun.com/jerryliang/chatglm2:last

