name: upload model to cos
on: 
  push:
    branches: [ model-upload-cos ]

jobs:
    sh:
        runs-on: ubuntu-latest
        env:
          secret_id: ${{secrets.qcloud_secret_id}}
          secret_key: ${{secrets.qcloud_secret_key}}
          region: ${{secrets.qcloud_region}}
        steps:
        - uses: actions/checkout@v2

        - name: clone chatglm2-32k
          run: |
            git clone https://huggingface.co/THUDM/chatglm2-6b-32k
            cd chatglm2-6b-32k && rm -rf .git

        - name: download requirements.txt
          run: |
            pip install -r requirements.txt
        
        - name: zip chatglm2-32k
          run: |
            zip -r chatglm2-6b-32K.zip chatglm2-6b-32k

        - name: upload chatglm2-32k
          run: |
            python3 main.py