name: docker build
on: 
  push:
    branches: [ chatglm2-6b-32K-tx ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Free Disk Space (Ubuntu)
          uses: jlumbroso/free-disk-space@main
          with:
            # this might remove tools that are actually needed,
            # if set to "true" but frees about 6 GB
            tool-cache: true
            
            # all of these default to true, but feel free to set to
            # "false" if necessary for your workflow
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: false
            swap-storage: true   

        - name: clone chatglm2-6b-32K
          run: |
            sudo apt-get update && sudo apt-get install git-lfs -y
            git lfs install
            git clone https://huggingface.co/THUDM/chatglm2-6b-32k
        # 设置 QEMU, 后面 docker buildx 依赖此.
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        
            # 设置 Docker buildx, 方便构建 Multi platform 镜像
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        
        # 登录腾讯docker
        - name: Login to Tencent docker
          uses: docker/login-action@v3
          with:
            registry: ccr.ccs.tencentyun.com
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        # 构建镜像, 并打 tag
        - name: Build docker image
          uses: docker/build-push-action@v3
          with:
            push: false
            tags: jerryliang/chatglm2:last

        - name: push image
          run: |
            docker image ls
            docker tag jerryliang/chatglm2:last ccr.ccs.tencentyun.com/jerryliang/chatglm2:last
            docker push ccr.ccs.tencentyun.com/jerryliang/chatglm2:last