name: upload model to cos
on: 
  push:
    branches: [ model-upload-server ]

jobs:
    sh:
        runs-on: ubuntu-latest
        steps:
          
        - name: Enable BBR congestion control
          run: |
            sudo modprobe tcp_bbr
            echo "tcp_bbr" | sudo tee -a /etc/modules
            echo "net.core.default_qdisc = fq" | sudo tee -a /etc/sysctl.conf
            echo "net.ipv4.tcp_congestion_control = bbr" | sudo tee -a /etc/sysctl.conf
            sudo sysctl -p

        - name: Free Disk Space (Ubuntu)
          uses: jlumbroso/free-disk-space@main
          with:
             #this might remove tools that are actually needed,
             #if set to "true" but frees about 6 GB
            tool-cache: true
            
             #all of these default to true, but feel free to set to
             #"false" if necessary for your workflow
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: true
            swap-storage: true 
            
        - name: Checkout
          uses: actions/checkout@v4

        - name: clone chatglm3-6B
          run: |
            git clone https://huggingface.co/THUDM/chatglm3-6b
            cd chatglm3-6b && rm -rf .git

        - name: loading id_rsa
          run: |
            echo "${{secrets.ID_RSA}}" >> ./ssh/id_rsa  
            chmod 600 ./ssh/id_rsa

        - name: rsync to server
          run: |
            rsync -avP chatglm3-6b root@${{secrets.SERVER_IP}}:/mnt/AI/